# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=8)),
                ('contact_number', models.IntegerField(default=0)),
            ],
        ),
    ]
